---
galaxy_info:
  author: EDB
  description: Setup fio
  company: "EnterpriseDB"

  license: BSD

  min_ansible_version: "2.8"

  platforms:
    - name: EL
      versions:
        - "8"

  galaxy_tags:
    - database

dependencies: []
