---
# Postgres EDB Postgres Advanced Server CentOS 7 and RHEL 7
# PG_RPMREPO: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
# Prior to 06/23/2020 - Redesign of EDB Portal
# PG_RPMREPO: "https://yum.enterprisedb.com/edb-repo-rpms/edb-repo-latest.noarch.rpm"
# After 06/23/2020 - Redesigned EDB Portal

# EDB repository username, password, subscription token and subscription plan
enable_edb_repo: true
repo_token: ""
repo_username: ""
repo_password: ""
repo_plan: "enterprise"

# TPA Specific token variable
tpa_subscription_token: ""

# PGD Specific variables
install_pgd: false
pgd_version: 5

# set to false only if you are using local repositories and do not need the PGDG and/or EPEL repositories.
# setting to false will result in failure to download required packages if access to local repos is not available
enable_pgdg_repo: true
enable_epel_repo: true

# setting validate_only to true allows you to validate setup on an existing node
# use_validation flag applies to deployment configuration and validation after setup
validate_only: false
use_validation: true
remove_only: false

# EDB RPM Repo
edb_rpm_repo: "http://yum.enterprisedb.com/edbrepos/edb-repo-latest.noarch.rpm"
edb_gpg_key_8: "https://yum.enterprisedb.com/ENTERPRISEDB-GPG-KEY"
edb_2q_base_repo_link: "https://techsupport.enterprisedb.com/api/repository/{{ tpa_subscription_token }}/products"
edb_2q_repositories:
  - bdr4/release
  - harp/release
edb_repo_base_download: "https://downloads.enterprisedb.com/{{ repo_token }}"
edb_repo_script_link: "{{ edb_repo_base_download }}/{{ repo_plan }}/setup.{{ 'rpm' if ansible_os_family == 'RedHat' else 'deb' }}.sh"

# EDB postgres_distributed RPM repo links
pgd_rpm_repo:
  - name: "enterprisedb-postgres_distributed-x86_64"
    description: "EDB Postgres Distributed Repo For x86_64"
    repo_url: "{{ edb_repo_base_download }}/postgres_distributed/rpm/el/{{ ansible_distribution_major_version }}/x86_64"
  - name: "enterprisedb-postgres_distributed-noarch"
    description: "EDB Postgres Distributed Repo For noarch"
    repo_url: "{{ edb_repo_base_download }}/postgres_distributed/rpm/el/{{ ansible_distribution_major_version }}/noarch"
edb_pgd_rpm_gpg_key: "{{ edb_repo_base_download }}/postgres_distributed/gpg.key"

# debian/ubuntu Repo
edb_deb_repo_url: "deb [arch=amd64] https://apt.enterprisedb.com/{{ ansible_distribution_release }}-edb/ {{ ansible_distribution_release }} main"
edb_deb_9_base_repo_url: "https://{{ repo_username }}:{{ repo_password }}@apt.enterprisedb.com/{{ ansible_distribution_release }}-edb/"
edb_deb_9_repo_url: "deb {{ edb_deb_9_base_repo_url }} {{ ansible_distribution_release }} main"
edb_deb_keys: "https://apt.enterprisedb.com/edb-deb.gpg.key"
edb_auth_conf: "/etc/apt/auth.conf.d/edb.conf"
edb_auth_conf_url: "machine apt.enterprisedb.com"

pg_deb_repo_url: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
pg_deb_keys: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"

# Postgresql Repos x86
pg_rpm_repo_7_x86_64: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
pg_rpm_repo_8_x86_64: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
pg_rpm_repo_9_x86_64: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
pg_gpg_key_8_x86_64: "https://yum.postgresql.org/keys/RPM-GPG-KEY-PGDG"
# Postgresql Repos aarch64
pg_rpm_repo_8_aarch64: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-aarch64/pgdg-redhat-repo-latest.noarch.rpm"
pg_rpm_repo_9_aarch64: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-aarch64/pgdg-redhat-repo-latest.noarch.rpm"
pg_gpg_key_8_aarch64: "https://yum.postgresql.org/keys/RPM-GPG-KEY-PGDG-AARCH64-RHEL8"
pg_gpg_key_9_aarch64: "https://yum.postgresql.org/keys/RPM-GPG-KEY-PGDG-AARCH64-RHEL9"

# epel Repo
epel_repo_7: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
epel_repo_8: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm"
epel_repo_9: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm "
epel_gpg_key_8: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8"
epel_gpg_key_9: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9"

os: ""
pg_type: "PG"

apt_additional_repos: []
yum_additional_repos: []

supported_os:
  - CentOS7
  - CentOS8
  - RedHat7
  - RedHat8
  - RedHat9
  - Ubuntu20
  - Ubuntu22
  - Debian9
  - Debian10
  - Rocky8
  - Rocky9
  - AlmaLinux8
  - OracleLinux7

supported_pg_type:
  - EPAS
  - PG
  - DBaaS

supported_pg_version:
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
