---
# postgres settings
os: ""
pg_type: PG
pg_version: 12
pg_ssl: true

disable_logging: yes
use_hostname: false

pass_dir: "~/.edb"

pg_wal: ""
pg_data: "/var/lib/pgsql/{{ pg_version }}/data"
pg_default_data: "/var/lib/pgsql/{{ pg_version }}/data"
pg_encoding: ""

# log directory and filename
pg_log: "/var/log/postgres"
pg_log_filename: "postgresql-%a.log"

# postgres service
pg_service: "postgresql-{{ pg_version }}"

# required & optional directories
pg_user_home: "/var/lib/pgsql"
pg_bin_path: "/usr/pgsql-{{ pg_version }}/bin"
pg_initdb: "{{ pg_bin_path }}/postgresql-{{ pg_version }}-setup initdb"
pg_initdb_options: "--encoding=UTF-8 --locale=en_US.UTF-8 --auth=peer --auth-local=scram-sha-256 --auth-host=scram-sha-256 --data-checksums"

# unix socket domain directories
pg_unix_socket_directories:
  - "/var/run/postgresql"

# postgres port
pg_port: 5432

# postgres database
pg_database: "postgres"

# postgres user
pg_owner: "postgres"
pg_group: "postgres"

# postgres superuser
pg_superuser: "postgres"
pg_superuser_password: ""
pg_random_password: true

# Input variables
input _user: ""
input_password: ""

etc_hosts_lists: []

supported_os:
  - CentOS7
  - CentOS8
  - RedHat7
  - RedHat8
  - Ubuntu20
  - Debian9
  - Debian10

supported_pg_type:
  - EPAS
  - PG

supported_pg_version:
  - 10
  - 11
  - 12
  - 13
