---
- hosts: localhost
  name: Configure Postgres SQL Replication on Instances
  #connection: local
  become: true
  gather_facts: no

  # When using collections
  #collections:
  #    - edb_devops.edb_postgres

  vars_files:
    - hosts.yml

  pre_tasks:
      - name: Initialize the user defined variables
        set_fact:
            os: "CentOS7"
            pg_version: 12
            pg_type: "EPAS"
            yum_username: ""
            yum_password: ""

  roles:
    - setup_repo
    - install_dbserver
    - init_dbserver
    - setup_replication
    - setup_efm
    - setup_pem
    - manage_dbserver
    - setup_pgbouncer
    - manage_pgbouncer_databases
