---
galaxy_info:
  role_name: setup_pgbackrestserver
  namespace: edb_postgres
  author: EDB
  description: Setup pgBackRest server
  company: "EnterpriseDB"

  license: BSD

  min_ansible_version: 2.8

  platforms:
    - name: CentOS
      versions:
        - 7
        - 8
    - name: Red Hat
      versions:
        - 7
        - 8
    - name: Debian
      versions:
        - 10

  galaxy_tags:
    - database
    - postgresql
    - postgres
    - backup
    - pgbackrest

dependencies: []
