---
- name: "Install EPAS Packages"
  ansible.builtin.package:
    name:
      - python3-pip
      - python3-psycopg2
      - edb-as{{ pg_version }}-server
      - edb-as{{ pg_version }}-server-core
      - edb-as{{ pg_version }}-server-client
      - edb-as{{ pg_version }}-server-indexadvisor
      - edb-as{{ pg_version }}-server-sqlprofiler
      - edb-as{{ pg_version }}-server-sqlprotect
    state: present
    update_cache: true
  become: true
  notify:
    - Stop EPAS service
    - Drop the default EPAS debian database

- name: "Install EPAS < 14 Packages"
  ansible.builtin.package:
    name:
      - edb-as{{ pg_version }}-server-edb-modules
    state: present
    update_cache: true
  become: true
  when: >-
    pg_version|int < 14

- name: "Install EPAS >= 14 Packages"
  ansible.builtin.package:
    name:
      - edb-as{{ pg_version }}-server-edb-wait-states
    state: present
    update_cache: true
  become: true
  when: >-
    pg_version|int >= 14

- name: Install sslutils
  ansible.builtin.package:
    name:
      - edb-as{{ pg_version }}-server-sslutils
    state: present
  become: true
  when: pg_ssl

- name: Install python-psycopg2
  ansible.builtin.package:
    name:
      - python-psycopg2
      - python-ipaddress
    state: present
    update_cache: true
  when: os in ['Ubuntu18', 'Debian9', 'Debian10']
  become: true

- name: "Install PGD packages for EPAS >= 14"
  ansible.builtin.package:
    name:
      - edb-bdr{{ pgd_version }}-{{ pg_type | lower }}{{ pg_version }}
      - edb-bdr{{ pgd_version }}-{{ pg_type | lower }}{{ pg_version }}-debuginfo
    state: present
  become: true
  when: >-
    pg_version|int >= 14
    and install_pgd|bool

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
