---
- name: Install python packages
  package:
    name:
      - python-pip
      - python2-psycopg2
      - python-ipaddress
    state: present
  when: os in ['RedHat7','CentOS7']
  become: yes

- name: Install python packages
  package:
    name:
      - python3-pip
      - python3-psycopg2
    state: present
  when: os in ['RedHat8','CentOS8','Rocky8']
  become: yes

- name: "Install EPAS 10 packages"
  package:
    name:
      - edb-as{{ pg_version }}-server
      - edb-as{{ pg_version }}-server-core
      - edb-as{{ pg_version }}-server-contrib
      - edb-as{{ pg_version }}-server-libs
      - edb-as{{ pg_version }}-server-client
      - edb-as{{ pg_version }}-server-sslutils
      - edb-as{{ pg_version }}-server-indexadvisor
      - edb-as{{ pg_version }}-server-sqlprofiler
      - edb-as{{ pg_version }}-server-sqlprotect
      - edb-as{{ pg_version }}-server-sslutils
    state: present
  become: yes
  when: >-
    pg_version|int < 11

- name: "Install EPAS 11,12,13 packages"
  package:
    name:
      - edb-as{{ pg_version }}-server
      - edb-as{{ pg_version }}-server-core
      - edb-as{{ pg_version }}-server-edb-modules
      - edb-as{{ pg_version }}-server-contrib
      - edb-as{{ pg_version }}-server-libs
      - edb-as{{ pg_version }}-server-client
      - edb-as{{ pg_version }}-server-llvmjit
      - edb-as{{ pg_version }}-server-sslutils
      - edb-as{{ pg_version }}-server-indexadvisor
      - edb-as{{ pg_version }}-server-sqlprofiler
      - edb-as{{ pg_version }}-server-sqlprotect
      - edb-as{{ pg_version }}-server-sslutils
    state: present
  become: yes
  when: >-
    pg_version|int > 10 and pg_version|int < 14

- name: "Install EPAS >= 14 packages"
  package:
    name:
      - edb-as{{ pg_version }}-server
      - edb-as{{ pg_version }}-server-core
      - edb-as{{ pg_version }}-server-contrib
      - edb-as{{ pg_version }}-server-libs
      - edb-as{{ pg_version }}-server-client
      - edb-as{{ pg_version }}-server-llvmjit
      - edb-as{{ pg_version }}-server-sslutils
      - edb-as{{ pg_version }}-server-indexadvisor
      - edb-as{{ pg_version }}-server-sqlprofiler
      - edb-as{{ pg_version }}-server-sqlprotect
      - edb-as{{ pg_version }}-server-sslutils
      - edb-as{{ pg_version }}-server-edb_wait_states
    state: present
  become: yes
  when: >-
    pg_version|int >= 14
