---
- name: Ensure core dump directory exists
  file:
    path: "{{ core_dump_directory }}"
    owner: root
    mode: "0733"
    state: directory
  become: yes
  no_log: "{{ disable_logging }}"

- name: Add core dump parameters in sysctl.conf
  ansible.posix.sysctl:
    name: "{{ line_item.name }}"
    value: "{{ line_item.value }}"
    state: "{{ line_item.state|default('present') }}"
    reload: yes
  with_items: "{{ sysctl_params }}"
  loop_control:
    loop_var: line_item
  become: yes
  no_log: "{{ disable_logging }}"

- name: Update limits.conf file
  community.general.pam_limits:
    domain: "{{ pg_owner }}"
    limit_type: soft
    limit_item: core
    value: unlimited
  become: yes
  no_log: "{{ disable_logging }}"
