---
- name: Install Postgres
  ansible.builtin.package:
    name:
      - ca-certificates
      - python3-pycurl
      - python3-psycopg2
      - postgresql-{{ pg_version }}
      - postgresql-{{ pg_version }}
      - postgresql-server-dev-{{ pg_version }}
    state: present
    update_cache: true
  register: install_package
  become: true
  notify:
    - Stop PG service
    - Drop the default PG debian database

- name: Install sslutils
  ansible.builtin.package:
    name:
      - postgresql-{{ pg_version }}-sslutils
    state: present
    update_cache: true
  become: true
  when: pg_ssl

- name: Install python-psycopg2
  ansible.builtin.package:
    name:
      - python-psycopg2
      - python-ipaddress
    state: present
    update_cache: true
  when: os in ['Ubuntu18','Debian9','Debian10']
  become: true

- name: "Install BDR packages for PG >= 14"
  ansible.builtin.package:
    name:
      - edb-bdr{{ bdr_version }}-{{ pg_type | lower }}{{ pg_version }}
      - edb-bdr{{ bdr_version }}-{{ pg_type | lower }}{{ pg_version }}-debuginfo
    state: present
  become: true
  when: >-
    pg_version|int >= 14
    and install_bdr_packages|bool

- name: Flush handlers
  meta: flush_handlers
