---
- name: check if agent was registered
  stat:
    path: "{{ pem_agent_bin_path }}/../etc/.agentregistered"
  become: yes
  register: pemagent_configured

- name: install pem agent
  shell: |
    set -o pipefail
    set -eu
    PEM_SERVER_PASSWORD={{ pg_pem_admin_password }} \
    {{ pem_agent_bin_path }}/pemworker \
         --register-agent \
         --display-name {{ item.key }} \
         --pem-user {{ pg_pem_admin_user }} \
         --pem-server {{ pem_server_private_ip }} \
         --pem-port {{ pg_port }} \
         --allow_server_restart true \
         --allow-batch-probes true \
         --batch-script-user root \
    && touch {{ pem_agent_bin_path }}/../etc/.agentregistered
  args:
    executable: /bin/bash
    creates: "{{ pem_agent_bin_path }}/../etc/.agentregistered"
  register: output
  changed_when: "'Postgres Enterprise Manager Agent registered successfully!' in output.stdout"
  failed_when: "'Postgres Enterprise Manager Agent registered successfully!' not in output.stdout"
  when: not pemagent_configured.stat.exists
  become: yes

- name: start the pem service
  systemd:
    name: "{{ pem_agent_service }}"
    daemon_reload: yes
    state: started
  become: yes
