---
pgpool2_version: 4.3
# We don't have the choice of the version with community PostgreSQL
pgpool2_package_name: "pgpool2"
pgpool2_configuration_file: "/etc/pgpool2/pgpool.conf"
pgpool2_user: "postgres"
pgpool2_group: "postgres"

# Systemd unit file
pgpool2_systemd_config_file: "/etc/systemd/system/pgpool2.service.d/pgpool2.conf"
pcp_configuration_file: "/etc/pgpool2/pcp.conf"
pgpool2_pid_file_name: "/var/run/pgpool2/pgpool.pid"
pgpool2_logdir: "/var/log/pgpool2"
# Directory containing SSL keys and certs
pgpool2_ssl_dir: "/etc/pgpool2/ssl"
pgpool2_bin_path: "/usr/sbin"

# pgpool service name
pgpool2_service_name: "pgpool2"

# pgpool environment file
pgpool2_environment_file: "/etc/default/pgpool2"

pcp_socket_dir: "/tmp"
pgpool2_socket_dir: "/tmp"

pgpool2_node_id_file: "/etc/pgpool2/pgpool_node_id"