---
dbt2_version: "0.45.1"
dbt2_user: dbt2
dbt2_user_home: /home/dbt2
pg_dbt2_user: dbt2
pg_dbt2_dbname: dbt2
pg_dbt2_user_password: ""
pg_version: 14

supported_os:
  - CentOS7
  - CentOS8
  - RedHat7
  - RedHat8
  - Rocky8
  - OracleLinux7
