---
pgpool2_configuration_file: "/etc/pgpool-II/pgpool.conf"
pgpool2_pool_passwd_file: "/etc/pgpool-II/pool_passwd"
pgpool2_user: "postgres"
pgpool2_group: "postgres"
pgpool2_bin_path: "/usr/bin"
pcp_configuration_file: "/etc/pgpool-II/pcp.conf"
pgpool2_service_name: "pgpool-II"