- name: Update /etc/hosts file, based on variable etc_hosts_list
  ansible.builtin.lineinfile:
    path: "/etc/hosts"
    line: "{{ item }}"
  loop: "{{ etc_hosts_lists }}"

- name: Update /etc/hosts file, based on the inventory
  ansible.builtin.lineinfile:
    path: "/etc/hosts"
    line: "{{ item.private_ip }} {{ item.inventory_hostname }}"
    regexp: ".*\\s{{ item.inventory_hostname | regex_escape() }}$"
  loop: "{{ lookup('tmax_opensql.postgres.all_nodes', wantlist=True) }}"

- name: Update system hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
