---
- name: Add password in pgpass
  ansible.builtin.include_role:
    name: manage_dbserver
    tasks_from: manage_pgpass
  vars:
    pg_pgpass_values:
      - user: "{{ pg_replication_user }}"
        password: "{{ pg_replication_user_password }}"
        create: true
  no_log: "{{ disable_logging }}"

- name: Include setup_tde tasks
  ansible.builtin.include_tasks: setup_tde.yml
  when:
    - edb_enable_tde
    - pg_version|int >= 15
    - pg_type == 'EPAS'

- name: Create standby
  ansible.builtin.shell: >
    PGAPPNAME={{ inventory_hostname }} {{ pg_basebackup }}
  args:
    creates: "{{ pg_data }}/PG_VERSION"
  become: true
  become_user: "{{ pg_owner }}"
  async: 180000
  poll: 60

- name: Enable and start the service
  ansible.builtin.systemd:
    name: "{{ pg_service }}"
    daemon_reload: true
    state: started
    enabled: true
  become: true

- name: Update standby hba config
  ansible.builtin.include_role:
    name: manage_dbserver
    tasks_from: manage_hba_conf
  vars:
    pg_hba_ip_addresses: "{{ pg_allow_ip_addresses }}"
  no_log: "{{ disable_logging }}"
