---
- name: Define pg_basebackup command.
  set_fact:
    pg_basebackup: "{{ pg_basebackup + ' -D ' + pg_data }}"

- name: Verify pg_wal and accordingly add the in the pg_basebackup
  set_fact:
    pg_basebackup: "{{ pg_basebackup + ' --waldir=' + pg_wal }}"
  when: pg_wal|length > 0  and not pg_data in pg_wal

- name: Add slot_name in pg_basebackup
  set_fact:
    pg_basebackup: "{{ pg_basebackup + ' --slot=' }}{{ inventory_hostname | regex_replace('[^a-zA-Z0-9_]', '_') }}"
  when: use_replication_slots

- name: Set replication user information
  set_fact:
    pg_basebackup: "{{ pg_basebackup + ' --username=' + pg_replication_user }}"
  when: pg_replication_user|length > 0

- name: Set host and port
  set_fact:
    pg_basebackup: "{{ pg_basebackup + ' --host=' + hostvars[inventory_hostname].upstream_node_private_ip + ' --port=' + pg_port | string }}"
  when:
    - not use_hostname|bool
    - hostvars[inventory_hostname].upstream_node_private_ip is defined

- name: Set host and port
  set_fact:
    pg_basebackup: "{{ pg_basebackup + ' --host=' + upstream_hostname + ' --port=' + pg_port | string }}"
  when:
    - use_hostname|bool
    - hostvars[inventory_hostname].upstream_node_private_ip is defined

- name: Use other supplied options if given
  set_fact:
    pg_basebackup: "{{ pg_basebackup + ' ' + pg_basebackup_options }}"
  when: pg_basebackup_options|length > 0
