---
# RPM package name
pgbouncer_package_name: "edb-pgbouncer120"

# PgBouncer service name
pgbouncer_service_name: "edb-pgbouncer-1.20"

# PgBouncer system user & group
pgbouncer_user: "enterprisedb"
pgbouncer_group: "enterprisedb"

# PgBouncer authentication part
pgbouncer_auth_file: "/etc/edb/pgbouncer1.20/userlist.txt"

# PID file
pgbouncer_pid_file: "/run/edb/pgbouncer1.20/edb-pgbouncer-1.20.pid"
# Configuration file
pgbouncer_config_file: "/etc/edb/pgbouncer1.20/edb-pgbouncer-1.20.ini"
# Log file
pgbouncer_log_file: "/var/log/edb/pgbouncer1.20/edb-pgbouncer-1.20.log"
# Databases configuration file
pgbouncer_databases_file: "/etc/edb/pgbouncer1.20/databases.ini"

# SSL dir
pgbouncer_ssl_dir: "/etc/edb/pgbouncer1.20/ssl"
