---

- name: Remove PG repos and epel-release packages
  yum:
    name:
      - pgdg-redhat-repo
      - epel-release
    state: removed
  become: yes

- name: Remove PGDG repo file
  file:
    path: /etc/yum.repos.d/pgdg-redhat-all.repo
    state: absent
  become: yes
