---

- name: Remove epel-release and edb-repo packages
  yum:
    name:
      - epel-release
      - edb-repo
    state: absent
  become: yes

- name: Remove edb.repo file
  file:
    path: /etc/yum.repos.d/edb.repo
    state: absent
  become: yes

- name: Remove edb.repo file
  file:
    path: /etc/yum.repos.d/edb.repo.rpmsave
    state: absent
  become: yes
