---
- name: Manage optional users
  postgresql_user:
    name: "{{ line_item.name }}"
    password: "{{ line_item.pass | default(omit) }}"
    encrypted: "{{ line_item.encrypted | default(omit) }}"
    conn_limit: "{{ line_item.conn_limit | default(omit) }}"
    expires: "{{ line_item.expires | default(omit) }}"
    priv: "{{ line_item.priv | default(omit) }}"
    role_attr_flags: "{{ line_item.role_attr_flags | default(omit) }}"
    groups: "{{ line_item.groups | default(omit) }}"
    port: "{{ pg_port }}"
    db: "{{ pg_database }}"
    state: "{{ line_item.state | default('present') }}"
    login_user: "{{ pg_owner }}"
    login_unix_socket: "{{ pg_unix_socket_directories[0] }}"
  no_log: "{{ disable_logging }}"
  become: yes
  become_user: "{{ pg_owner }}"
  with_items: "{{ pg_users }}"
  loop_control:
    loop_var: line_item
  when: pg_users|length > 0
