---
# CAMO Commit Scope
- name: Run query to check if PGD parent group exists or not
  ansible.builtin.include_role:
    name: manage_dbserver
    tasks_from: execute_sql_scripts
  vars:
    pg_query:
      - query: "SELECT COUNT(1) FROM bdr.node_group WHERE node_group_name  = '{{ item.parent_group }}'"
        db: "{{ pgd_cluster_database }}"

- name: Store status of existence of PGD parent group
  ansible.builtin.set_fact:
    _pgd_camo_parentgroup_exists: "{{ sql_query_output.results[0].query_result[0].count | int }}"

- name: Run query to check if PGD CAMO commit scope origin node group
  ansible.builtin.include_role:
    name: manage_dbserver
    tasks_from: execute_sql_scripts
  vars:
    pg_query:
      - query: "SELECT COUNT(1) FROM bdr.node_group WHERE node_group_name  = '{{ item.cs_origin_node_group }}'"
        db: "{{ pgd_cluster_database }}"

- name: Store status of existence of PGD commit scope origin node group
  ansible.builtin.set_fact:
    _pgd_camo_originnodegroup_exists: "{{ sql_query_output.results[0].query_result[0].count | int }}"

- name: Create PGD Cluster commit scope origin node group
  ansible.builtin.include_role:
    name: manage_dbserver
    tasks_from: execute_sql_scripts
  vars:
    pg_query:
      - query: "SELECT bdr.create_node_group(node_group_name := '{{ item.cs_origin_node_group }}',
                                      parent_group_name := '{{ item.parent_group }}',
                                      join_node_group := false
                                      )"
        db: "{{ pgd_cluster_database }}"
    ignore_query_execution_error: false
  when:
    - inventory_hostname == item.member_nodes[0]
    - _pgd_camo_originnodegroup_exists|int == 0 and _pgd_camo_parentgroup_exists|int == 1
    - item.cs_type == 'CAMO'

- name: Run query to re-check if PGD CAMO commit scope origin node group
  ansible.builtin.include_role:
    name: manage_dbserver
    tasks_from: execute_sql_scripts
  vars:
    pg_query:
      - query: "SELECT COUNT(1) FROM bdr.node_group WHERE node_group_name  = '{{ item.cs_origin_node_group }}'"
        db: "{{ pgd_cluster_database }}"

- name: Store status of existence of PGD commit scope origin node group
  ansible.builtin.set_fact:
    _pgd_camo_originnodegroup_exists: "{{ sql_query_output.results[0].query_result[0].count | int }}"

- name: Switch primary node towards PGD node sub group with two nodes when CAMO
  ansible.builtin.include_role:
    name: manage_dbserver
    tasks_from: execute_sql_scripts
  vars:
    pg_query:
      - query: "SELECT bdr.switch_node_group(node_group_name := '{{ item.cs_origin_node_group }}',
                                      wait_for_completion := true
                                      )"
        db: "{{ pgd_cluster_database }}"
    ignore_query_execution_error: false
  when:
    - inventory_hostname == node
    - _pgd_camo_originnodegroup_exists|int == 1 and _pgd_camo_parentgroup_exists|int == 1
    - item.cs_type == 'CAMO'
  loop: "{{ item.member_nodes }}"
  loop_control:
    loop_var: node

- name: Configure PGD Cluster with a CAMO Commit Scope
  ansible.builtin.include_role:
    name: manage_dbserver
    tasks_from: execute_sql_scripts
    apply:
      throttle: 1
  vars:
    pg_query:
      - query: "SELECT bdr.add_commit_scope(commit_scope_name := '{{ item.cs_name }}',
                                          origin_node_group := '{{ item.cs_origin_node_group }}',
                                          rule := '{{ item.cs_rule }}'
                                         )"
        db: "{{ pgd_cluster_database }}"
    ignore_query_execution_error: false
  when:
    - inventory_hostname == node
    - _pgd_camo_originnodegroup_exists|int == 1 and _pgd_camo_parentgroup_exists|int == 1
  loop: "{{ item.member_nodes }}"
  loop_control:
    loop_var: node

- name: Run query to check if PGD CAMO commit scope exists or not
  ansible.builtin.include_role:
    name: manage_dbserver
    tasks_from: execute_sql_scripts
  vars:
    pg_query:
      - query: "SELECT COUNT(1) FROM bdr.commit_scopes WHERE commit_scope_name  = '{{ item.cs_name }}'"
        db: "{{ pgd_cluster_database }}"

- name: Store status of existence of PGD CAMO commit scope
  ansible.builtin.set_fact:
    _pgd_camoscope_exists: "{{ sql_query_output.results[0].query_result[0].count | int }}"

- name: Configure PGD Cluster default CAMO Commit Scope
  ansible.builtin.include_role:
    name: manage_dbserver
    tasks_from: execute_sql_scripts
    apply:
      throttle: 1
  vars:
    pg_query:
      - query: "SELECT bdr.alter_node_group_option(node_group_name := '{{ item.cs_origin_node_group }}',
                                      config_key := 'default_commit_scope',
                                      config_value := '{{ item.cs_name }}'
                                      )"
        db: "{{ pgd_cluster_database }}"
    ignore_query_execution_error: false
  when:
    - item.default_group_cs|bool == True
    - item.cs_type|string == 'CAMO'
    - _pgd_camoscope_exists|int == 1 and _pgd_camo_originnodegroup_exists|int == 1

- name: Configure BDR 'default_streaming_mode' to off
  ansible.builtin.include_role:
    name: manage_dbserver
    tasks_from: execute_sql_scripts
    apply:
      throttle: 1
  vars:
    pg_query:
      - query: "SELECT bdr.alter_node_group_option(node_group_name := '{{ item.parent_group }}',
                                      config_key := 'streaming_mode',
                                      config_value := 'off'
                                      )"
        db: "{{ pgd_cluster_database }}"
    ignore_query_execution_error: false
  when:
    - item.default_group_cs|bool == true
    - item.cs_type|string == 'CAMO'
    - _pgd_camoscope_exists|int == 1 and _pgd_camo_originnodegroup_exists|int == 1

- name: ALTER max_prepared_transactions
  community.postgresql.postgresql_query:
    query: >-
      ALTER SYSTEM SET max_prepared_transactions = 100
    port: "{{ pg_port }}"
    db: "{{ pg_database }}"
    login_user: "{{ pg_owner }}"
    login_unix_socket: "{{ pg_unix_socket_directories[0] }}"
    autocommit: true
  no_log: "{{ disable_logging }}"
  become: true
  become_user: "{{ pg_owner }}"

- name: Restart the pg service
  ansible.builtin.systemd:
    name: "{{ pg_service }}"
    state: restarted
  become: true
