---
- name: Prepare hba non ssl list
  ansible.builtin.set_fact:
    pg_allow_ip_addresses: >-
      {{ pg_allow_ip_addresses | default([]) + [
        {
          "contype": "host",
          "users": pgd_replication_user,
          "source": node.private_ip + "/32",
          "databases": pgd_cluster_database
          },
        {
          "contype": "host",
          "users": pgd_replication_user,
          "source": node.private_ip + "/32",
          "databases": "replication"
          },
          {
           "contype": "host",
           "users": pgd_replication_user,
           "source": node.private_ip + "/32",
           "databases": pg_database
           }
        ] }}
  when: not pg_ssl
  loop: "{{ pgd_cluster_nodes }}"
  loop_control:
    loop_var: node
  run_once: true
  no_log: "{{ disable_logging }}"

- name: Prepare hba ssl list
  ansible.builtin.set_fact:
    pg_allow_ip_addresses: >-
      {{ pg_allow_ip_addresses | default([]) + [
        {
          "users": pgd_replication_user,
          "source": node.private_ip + "/32",
          "databases": pgd_cluster_database
          },
          {
          "contype": "host",
          "users": pgd_replication_user,
          "source": node.private_ip + "/32",
          "databases": "replication"
          },
          {
           "users": pgd_replication_user,
           "source": node.private_ip + "/32",
           "databases": pg_database
           }
        ] }}
  when: pg_ssl
  loop: "{{ pg_cluster_nodes }}"
  loop_control:
    loop_var: node
  run_once: true
  no_log: "{{ disable_logging }}"

- name: Update PGD node hba config
  ansible.builtin.include_role:
    name: manage_dbserver
    tasks_from: manage_hba_conf
  vars:
    pg_hba_ip_addresses: "{{ pg_allow_ip_addresses }}"
  no_log: "{{ disable_logging }}"