---
- hosts: all
  name: Postgres deployement playbook
  become: yes
  gather_facts: yes

  # When using collections
  #collections:
  #    - edb_devops.edb_postgres

  pre_tasks:
    - name: Initialize the user defined variables
      set_fact:
        pg_version: 13
        pg_type: "PG"
        repo_username: ""
        repo_password: ""
        disable_logging: false

  roles:
    - role: setup_repo
      when: "'setup_repo' in host_supported_roles"
    - role: install_dbserver
      when: "'install_dbserver' in host_supported_roles"
    - role: init_dbserver
      when: "'init_dbserver' in host_supported_roles"
    - role: autotuning
      when: "'autotuning' in host_supported_roles"
    - role: setup_replication
      when: "'setup_replication' in host_supported_roles"
    - role: setup_efm
      when: "'setup_efm' in host_supported_roles"
    - role: setup_pemserver
      when: "'setup_pemserver' in host_supported_roles"
    - role: setup_pemagent
      when: "'setup_pemagent' in host_supported_roles"
