---
# pgBackRest RPM package info
pgbackrest_package_name: "pgbackrest"

# replication user setup in postgresql.conf
replication_user: "repuser"

# spool directory - only used with archive-async
pgbackrest_spool_directory: "/var/spool/pgbackrest"
use_patroni: false

# number of parallel processes to be used during backup and recovery
# recommended to not use more than 25% of available CPU for the backup command
# only set if archive method is async.
process_max_backup: 3
process_max_recovery: 3

etc_hosts_lists: []
use_hostname: true
update_etc_file: true

# setting validate_only to true allows you to validate setup on an existing node
# use_validation flag applies to deployment configuration and validation after setup
validate_only: false
use_validation: true
remove_only: false

supported_os:
  - CentOS7
  - CentOS8
  - RHEL7
  - RHEL8
  - Rocky8
  - AlmaLinux8
  - Debian10
  - Ubuntu20
