---
# postgres settings
os: ""
pg_type: PG
pg_version: 12
pg_ssl: true

force_initdb: false
use_hostname: false

pass_dir: "~/.edb"

pg_wal: ""
pg_data: "/var/lib/pgsql/{{ pg_version }}/data"
pg_default_data: "/var/lib/pgsql/{{ pg_version }}/data"
pg_encoding: ""

# log directory and filename
pg_log: "/var/log/postgres"
pg_log_filename: "postgresql-%a.log"

# postgres service
pg_service: "postgresql-{{ pg_version }}"

# required & optional directories
pg_user_home: "/var/lib/pgsql"
pg_bin_path: "/usr/pgsql-{{ pg_version }}/bin"
pg_initdb: "{{ pg_bin_path }}/postgresql-{{ pg_version }}-setup initdb"
pg_initdb_options: "-k -A scram-sha-256 --encoding=UTF-8 --locale=en_US.UTF-8 --auth-local=peer --pwfile /dev/zero"

# unix socket domain directories
pg_unix_socket_directories:
  - "/var/run/postgresql"

# postgres port
pg_port: 5432

# postgres database
pg_database: "postgres"

# postgres user
pg_owner: "postgres"
pg_group: "postgres"

# postgres superuser
pg_superuser: "postgres"
pg_superuser_password: ""
pg_random_password: false
pg_shared_libraries_list:
  - "$libdir/pg_stat_statements"
