---
deb_cluster_name: "main"
pg_wal: ""
pg_data: "/var/lib/postgresql/{{ pg_version }}/{{ deb_cluster_name }}"
pg_default_data: "/var/lib/postgresql/{{ pg_version }}/{{ deb_cluster_name }}"
pg_encoding: ""

# log directory and filename
pg_log: "/var/log/postgresql"
pg_log_filename: "postgresql-%a.log"

# postgres service
pg_service: "postgresql@{{ pg_version }}-{{ deb_cluster_name }}"

# required & optional directories
pg_user_home: "/var/lib/postgresql"
pg_bin_path: "/usr/lib/postgresql/{{ pg_version }}/bin"

# unix socket domain directories
pg_unix_socket_directories:
  - "/var/run/edb"

# postgres port
pg_port: 5444

pg_initdb_options: "-k -A scram-sha-256 --encoding=UTF-8 --locale=C.UTF-8 --auth-local=peer --pwfile /dev/zero"
pg_initdb: "/usr/bin/pg_createcluster -s {{ pg_unix_socket_directories[0] }} {{ pg_version }} {{ deb_cluster_name }} -- ${PGSETUP_INITDB_OPTIONS}"

# postgres database
pg_database: "postgres"

# postgres user
pg_owner: "postgres"
pg_group: "postgres"

# postgres superuser
pg_superuser: "postgres"
pg_superuser_password: ""
pg_random_password: false


pg_shared_libraries_list:
  - "$libdir/pg_stat_statements"
