---
- hosts: localhost
  #vars:
  #  ansible_python_interpreter: /usr/bin/python2
  name: install, configure, initialize and replicate epas 12 and efm 10 on instances
  #connection: local
  become: true
  gather_facts: no

  collections:
    -  edb_devops.edb_postgres

  vars_files:
    - hosts.yml

# internal processing purposes only
  pre_tasks:
    - name: initialize the user defined variables
      set_fact:
        os: "RHEL7"
        pg_version: 12
        pg_type: "EPAS"
        yum_username: ""
        yum_password: ""
  
   roles:
     - setup_repo
     - install_dbserver
     - init_dbserver
     - setup_replication
     - setup_efm
